# Generated by Django 5.2 on 2025-04-26 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportstaff',
            options={'verbose_name_plural': 'Support Staff'},
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='support_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'timestamp'], name='chat_chatme_room_id_b9cdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='chat_chatme_sender__3a9411_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'is_read'], name='chat_chatme_room_id_396ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['timestamp'], name='chat_chatme_timesta_f0eb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_id'], name='chat_chatro_room_id_c3a3db_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['user', 'is_active'], name='chat_chatro_user_id_dd850f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['support_staff', 'is_active'], name='chat_chatro_support_1ea27f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_active'], name='chat_chatro_is_acti_5637a4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_at'], name='chat_chatro_created_914abe_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['updated_at'], name='chat_chatro_updated_79f21c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportstaff',
            index=models.Index(fields=['is_online', 'is_available'], name='chat_suppor_is_onli_7813ae_idx'),
        ),
        migrations.AddIndex(
            model_name='supportstaff',
            index=models.Index(fields=['user'], name='chat_suppor_user_id_abc094_idx'),
        ),
    ]
